test:
  name: "basic"

  tasks:
  - name: run_command
    config:
      command:
      - "echo"
      - "hello!"
  - name: execution_is_healthy
  - name: consensus_is_healthy
  - name: both_are_synced
    config:
      consensus:
        percent: 100
      execution:
        percent: 100
  - name: run_command
    config:
      command:
      - "echo"
      - "done!"

execution:
  url: http://localhost:8545

consensus:
  url: http://localhost:5052
