execution:
  url: http://localhost:8545

consensus:
  url: http://localhost:5052

test:
  name: "basic"

  tasks:
  - name: execution_is_healthy
  - name: consensus_is_healthy
  - name: both_are_synced
    config:
      consensus:
        percent: 100
      execution:
        percent: 100

