endpoints:
  - name: "local"
    executionUrl: http://localhost:8545
    consensusUrl: http://localhost:5052

tests:
- name: "basic"
  timeout: 48h
  tasks:
  - name: check_clients_are_healthy
    title: "Consensus client is healthy"
    config:
      skipExecutionCheck: true

  - name: check_consensus_sync_status
    title: consensus is synced